name: Java CI - Ecotributario Pipeline

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build-and-process:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout del código
      uses: actions/checkout@v3

    - name: Configurar JDK
      uses: actions/setup-java@v3
      with:
        java-version: '17'
        distribution: 'temurin'

    - name: Ver estructura del proyecto
      run: ls -R
    - name: Inspeccionar contenido de src
      run: |
       echo "Contenido de src/:"
       find src -type f -print

    - name: Compilar proyecto Java (sin Maven)
      run: |
        mkdir -p out
        java_files=$(find src -name "*.java")
        if [ -z "$java_files" ]; then
          echo "No se encontraron archivos .java en src/"
          exit 1
        else
          echo " Archivos Java encontrados:"
          echo "$java_files"
          javac -d out $java_files
        fi
    - name: Ejecutar procesamiento de datos
      run: |
        echo "Procesando normativa y formularios..."
        echo "Generando informe..."
        mkdir -p reportes
        echo "Informe generado el $(date)" > reportes/informe.txt
        ls -l reportes

    - name: Subir artefactos del informe
      uses: actions/upload-artifact@v4
      with:
        name: informe-final
        path: reportes/informe.txt
