name: Validar Formularios

on:
  push:
    branches: [ main, desarrollo ]
  pull_request:
    branches: [ main, desarrollo ]

jobs:
  build-and-validate:
    runs-on: ubuntu-latest

    steps:
    - name: Clonar repositorio
      uses: actions/checkout@v3

    - name: Configurar JDK 17
      uses: actions/setup-java@v3
      with:
        java-version: '17'
        distribution: 'temurin'

    - name: Verificar existencia de clases de formularios
      run: |
        mkdir -p logs
        log_file=logs/validacion_formularios.log
        echo "Iniciando validación de formularios: $(date)" > $log_file
        if ls src/main/java/ecotributario/controllers/LoginController.java && \
           ls src/main/java/ecotributario/controllers/RegistroController.java; then
          echo " Formularios detectados correctamente." | tee -a $log_file
        else
          echo "Formularios no encontrados. Revisa la estructura del proyecto." | tee -a $log_file
          exit 1
        fi

    - name: Subir log de validación
      uses: actions/upload-artifact@v4
      with:
        name: log-validacion-formularios
        path: logs/validacion_formularios.log
