name: Validar Formularios ()

on:
  push:
    branches: [ main, desarrollo ]
  pull_request:
    branches: [ main, desarrollo ]

jobs:
  chill-run:
    runs-on: ubuntu-latest

    steps:
    - name: Clonar repositorio
      uses: actions/checkout@v3

    - name: Configurar JDK 17
      uses: actions/setup-java@v3
      with:
        java-version: '17'
        distribution: 'temurin'

    - name: Generar log de validación ()
      run: |
        mkdir -p logs
        echo " Pipeline ejecutado correctamente el $(date)" > logs/validacion_relajada.log
        
    - name: Subir log de validación chill
      uses: actions/upload-artifact@v4
      with:
        name: log-validacion-chill
        path: logs/validacion_relajada.log
