name: Validar Formularios

on:
  push:
    branches: [ main, desarrollo ]
  pull_request:
    branches: [ main, desarrollo ]

jobs:
  build-and-validate:
    runs-on: ubuntu-latest

    steps:
    - name: Clonar repositorio
      uses: actions/checkout@v3

    - name: Configurar JDK 17
      uses: actions/setup-java@v3
      with:
        java-version: '17'
        distribution: 'temurin'

    - name: Compilar proyecto
      run: mvn compile

    - name: Verificar existencia de clases de formularios
      run: |
        if ls src/main/java/ecotributario/controllers/LoginController.java && \
           ls src/main/java/ecotributario/controllers/RegistroController.java; then
          echo " Formularios detectados correctamente."
        else
          echo "Formularios no encontrados. Revisa la estructura del proyecto."
          exit 1
        fi
